### ISSUE TITLE
can only install in /usr/local/lib

### ISSUE THREAD

**Issue by tank-trax** [bruno-unna/euclidean-rhythms#7]
I was able to build this plugin but when I tried to install to `~/.lv2` was unable to

When invoking `meson install` it is asking for root access and this pop-up looks ominous

![image](https://user-images.githubusercontent.com/41337033/218893549-246b1e0b-aa00-47e2-a8cb-979631a07179.png)

Could you add an option for **target**?

**Comment by eli-schwartz** [comment]
> I was able to build this plugin but when I tried to install to `~/.lv2` was unable to

How did you try to install to `~/.lv2`? What actions did you take?

> Could you add an option for **target**?

This option already exists, if you run `meson configure` it will list some target directory options such as `prefix = /usr/local`. You should be able to just change that option.

**Comment by bruno-unna** [comment]
Thanks for the report @tank-trax. I can see how you would need root access if you want to install on the default `/usr/lib` base directory. However, as @eli-schwartz has stated, the option to change the target directory already exists, thanks to meson.

Regarding the ominous message, I just can't see how one thing (meson install) may lead to the other (formatting your USB memory stick). Would you please kindly describe the exact steps you took? That would help a lot.

**Comment by bruno-unna** [comment]
I've been able to build and install the plugin in a location other than the default, as per the build instructions.

@tank-trax: feel free to re-open if that doesn't fix the issue for you, or if you have more information to contribute to help the testing.

**Comment by bruno-unna** [comment]
@tank-trax: as it turns out, you were right all along. I've provided a fix.

In a nutshell: use the option `--libdir` for the first step (I think I've fixed it). For example, if you home directory is `/home/tank-trax`, you could use
`--libdir=/home/tank-trax/.lv2`. For the moment, there are two caveats:

- The directory needs to end in `.lv2` for this to work.
- The directory has to be explicitly stated, the special `~` can't be used.

Please try that and let me know if that works.

**Comment by tank-trax** [comment]
my apologies for not responding earlier... I ended up building it and putting it in another location under `/usr/local`  then manually moving it to `~/.lv2` and deleting whatever was under `/usr/local`

thanks for testing and fixing, I was pretty sure I followed the instructions to install locally but wanted to test it again before confirming.. you beat me to it :-) 

will give it a new try and let you know how it goes

**Comment by tank-trax** [comment]
it's still not working

must install under **/usr/local/lib/** and always asks for elevated privileges even if forced it to another location under **/home/username** 

![image](https://user-images.githubusercontent.com/41337033/221026588-0b1278b4-4989-4544-a1f8-68ed0dab7e5c.png)

and now there is a new error

`meson setup --native-file=environments/linux64.ini builddir`

![image](https://user-images.githubusercontent.com/41337033/221028469-f9fea2e1-39cd-4c2d-944d-3d9312ad174c.png)

```
WARNING: Library target 'euclidean' has 'name_prefix' set. Compilers may not find it from its '-leuclidean' linker flag in the 'euclidean.pc' pkg-config file.
WARNING: Library target 'euclidean' has 'name_prefix' set. Compilers may not find it from its '-leuclidean' linker flag in the 'euclidean-uninstalled.pc' pkg-config file.
```

**Comment by tank-trax** [comment]
I also noticed that when installed in `/usr/local/lib/lv2/` that the `euclidean.lv2` folder has user permissions, meaning that even though it required a PW to install, the folder can be deleted without elevated or root/admin privileges 

perhaps the python requires a user switch? I am not a developer so apologies if that sounds simplistic

**Comment by bruno-unna** [comment]
Thanks for testing. Those two warnings are understood, they are harmless. When libraries are created in linux systems, they usually are called `libXXX`, so that when those libraries are needed, developers can pass something like `-lXXX` to the compiler, and the compiler would translate that to the actual `libXXX.so` dependency. Plugins are different, though. They aren't called `libXXX`, they don't need the `lib` prefix. So I removed that prefix, and meson is warning me about it.

**Comment by bruno-unna** [comment]
The other issue might be a little more worrying. When you run `meson install` (I assume that's what you are running that produces the password prompt), you don't do that as the root user, right?

Are you a `sudo`er in your own machine? 

Have you tried running `meson setup --libdir /home/chris/.lv2 builddir`, as per the amended instructions? If that works, no attempt should be made by meson to install anything under `/usr/...`, and hence no escalation of privileges should occur.

**Comment by eli-schwartz** [comment]
> Plugins are different, though. They aren't called `libXXX`, they don't need the `lib` prefix. So I removed that prefix, and meson is warning me about it.

Well, specifically it's warning you that after doing so, you also created a pkg-config file describing how to link to it.

**Comment by bruno-unna** [comment]
> > Plugins are different, though. They aren't called `libXXX`, they don't need the `lib` prefix. So I removed that prefix, and meson is warning me about it.
> 
> Well, specifically it's warning you that after doing so, you also created a pkg-config file describing how to link to it.

Right... any chance for you to produce a pull-request to avoid it?

Sorry if I'm cheeky here, but it's obvious that you have much more experience with meson than I have. If not, could you point me in the right direction? Thanks in advance.
